#!/bin/sh

inc="`pkg-config --variable=includedir libxfce4panel-1.0`"/xfce4/libxfce4panel-1.0/libxfce4panel

for s in "${inc}"/*.h
do
	t="${s##*/}"
	
	t="${t%.h}"
	if [ "${t#xfce_panel_}" = "$t" ]
	then
		defs="${t/-/_}.defs"
		defs="${defs/-/_}"
		defs="${defs/-/_}"
		defs="${defs/-/_}"
		defs="${defs/xfce_panel_/}"
		defs="${defs/xfce_/}"
		[ "${defs}" = "internal_plugin.defs" ] && continue
		#[ "${defs}" = "plugin.defs" ] && continue
		
		python2 /usr/lib/python2.6/site-packages/gtk-2.0/codegen/h2def.py "$s" >"${defs}"
	fi
done

sed -e 's;\(XFCE_TYPE_EXTERNAL_PANEL_PLUGIN.*\)$;\1\
  (implements "XfcePanelPluginProvider")\
;' \
  plugin.defs >plugin.defs.n && mv plugin.defs.n plugin.defs.nn
