#!/bin/sh

inc="`pkg-config --variable=includedir libxfce4menu-0.1`"/xfce4

for s in "${inc}"/libxfce4menu-0.1/libxfce4menu/*.h
do
	if [ "${s%-private.h}" != "${s}" ]
	then
		continue
	fi
	t="${s##*/}"
	
	t="${t%.h}"
	
	if [ "${t#netk-}" = "$t" ]
	then
		defs="${t/-/_}.defs"
		defs="${defs/-/_}"  
		defs="${defs/-/_}"  
		defs="${defs/-/_}"  
		defs="${defs/-/_}"  
		# doesn't work: python -m codegen.h2def "$s" >"${defs}"
		python2 /usr/lib/python2.6/site-packages/gtk-2.0/codegen/h2def.py "$s" >"${defs}"
	fi
done

for s in xfce_*.defs
do
	t="${s#xfce_}"
	mv "$s" "$t"
done
