#!/bin/sh

inc="`pkg-config --variable=includedir libxfce4menu-1.0`"/xfce4

if [ -z "${inc}" ]
then
	inc="`pkg-config --variable=includedir libxfcegui4-1.0`"/xfce4
fi

for s in "${inc}"/libxfce4menu/*.h
do
	if [ "${s%-private.h}" != "${s}" ]
	then
		continue
	fi
	t="${s##*/}"
	
	t="${t%.h}"
	
	if [ "${t#netk-}" = "$t" ]
	then
		defs="${t/-/_}.defs"
		# doesn't work: python -m codegen.h2def "$s" >"${defs}"
		python /usr/lib/python2.5/site-packages/gtk-2.0/codegen/h2def.py "$s" >"${defs}"
	fi
done

#rm -f util.defs
#mmv -o 'xfce-*.defs' '#1.defs'
#rm -f libxfce4util.defs
#rm -f libxfce4util-config.defs
#rm -f generics.defs
#rm -f debug.defs
#cat menu.defs | grep -v '(gtype-id "MCS_TYPE_ACTION")' >menu.defs.new && mv mcs_client.defs.new mcs_client.defs

#cat mcs_common.defs | egrep -v '\(gtype-id "(MCS_TYPE_RESULT|MCS_TYPE_TYPE|MCS_TYPE_MANAGER_CHECK)"\)' >mcs_common.defs.new && mv mcs_common.defs.new mcs_common.defs

#  (release-func mcs_manager_destroy))

#sed -e 's;(define-object McsClient;(define-object Client;' xfce_mcs-client.defs > xfce_mcs-client.defs.new && mv xfce_mcs-client.defs.new xfce_mcs-client.defs
#sed -e 's;(define-object McsChannel;(define-object Channel;' xfce_mcs-channel.defs > xfce_mcs-channel.defs.new && mv xfce_mcs-channel.defs.new xfce_mcs-channel.defs
#sed -e 's;(define-object McsManager;(define-object Manager;' xfce_mcs-manager.defs > xfce_mcs-manager.defs.new && mv xfce_mcs-manager.defs.new xfce_mcs-manager.defs

