#!/bin/sh

for s in /usr/include/xfce4/libxfce4mcs/*.h
do
	t="${s##*/}"
	
	t="${t%.h}"
	
	if [ "${t#netk-}" = "$t" ]
	then
		defs="${t/-/_}.defs"
		python /usr/share/pygtk/2.0/codegen/h2def.py "$s" >"${defs}"
	fi
done
rm -f util.defs

#mmv -o 'xfce-*.defs' '#1.defs'
#rm -f libxfce4util.defs
#rm -f libxfce4util-config.defs
#rm -f generics.defs
#rm -f debug.defs
cat mcs_client.defs | grep -v '(gtype-id "MCS_TYPE_ACTION")' >mcs_client.defs.new && mv mcs_client.defs.new mcs_client.defs

cat mcs_common.defs | egrep -v '\(gtype-id "(MCS_TYPE_RESULT|MCS_TYPE_TYPE|MCS_TYPE_MANAGER_CHECK)"\)' >mcs_common.defs.new && mv mcs_common.defs.new mcs_common.defs

