/* Generated by GOB (v2.0.9) on Thu May 26 23:22:23 2005
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 9

#define selfp (self->_priv)

#include "xfce-mcs-manager.h"

#include "xfce-mcs-manager-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 1 "xfce-mcs-manager.gob"

/* TODO!!!!!! most manager stuff */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif
#ifdef HAVE_STRING_H
#include <string.h>
#endif
#include <gdk/gdkx.h>
#include <libxfce4mcs/mcs-common.h>

static void
weak_notify_cb(gpointer data, GObject *where_the_object_was)
{
	xfce_mcs_manager_vanish_object (XFCE_MCS_MANAGER (data), where_the_object_was);
}

/*
static void moo
{
	GdkWindow *gdkwin;
         
	gdkwin = gdk_window_lookup (window);
                         
	if (is_start)
		gdk_window_add_filter (gdkwin, client_event_filter, data);
	else
		gdk_window_remove_filter (gdkwin, client_event_filter, data);
}
                                                                         
static GdkFilterReturn
client_event_filter (GdkXEvent * xevent, GdkEvent * event, gpointer data)
{
	if (mcs_manager_process_event ((McsManager*) data, (XEvent *) xevent))
		return GDK_FILTER_REMOVE;
	else
		return GDK_FILTER_CONTINUE;
}
*/

static gboolean
my_ascii_strcasecmp(gconstpointer a, gconstpointer b)
{
	return g_ascii_strcasecmp ((gchar const *)a, (gchar const *)b) == 0;
}


#line 77 "xfce-mcs-manager.c"

#line 50 "xfce-mcs-manager.gob"

#include <gtk/gtk.h>
#include <libxfce4mcs/mcs-manager.h>
#include "xfce-mcs-channel.h"

#line 85 "xfce-mcs-manager.c"
/* self casting macros */
#define SELF(x) XFCE_MCS_MANAGER(x)
#define SELF_CONST(x) XFCE_MCS_MANAGER_CONST(x)
#define IS_SELF(x) XFCE_IS_MCS_MANAGER(x)
#define TYPE_SELF XFCE_TYPE_MCS_MANAGER
#define SELF_CLASS(x) XFCE_MCS_MANAGER_CLASS(x)

#define SELF_GET_CLASS(x) XFCE_MCS_MANAGER_GET_CLASS(x)

/* self typedefs */
typedef XfceMcsManager Self;
typedef XfceMcsManagerClass SelfClass;

/* here are local prototypes */
static void xfce_mcs_manager_class_init (XfceMcsManagerClass * c) G_GNUC_UNUSED;
static void xfce_mcs_manager_init (XfceMcsManager * self) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_new xfce_mcs_manager_new
#define self_vanish_object xfce_mcs_manager_vanish_object
#define self_add_channel xfce_mcs_manager_add_channel
#define self_delete_channel xfce_mcs_manager_delete_channel
#define self_get_setting xfce_mcs_manager_get_setting
#define self_set_setting xfce_mcs_manager_set_setting
#define self_delete_setting xfce_mcs_manager_delete_setting
#define self_notify xfce_mcs_manager_notify
#define self_set_setting_string xfce_mcs_manager_set_setting_string
#define self_set_setting_int xfce_mcs_manager_set_setting_int
#define self_set_setting_color xfce_mcs_manager_set_setting_color
GType
xfce_mcs_manager_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (XfceMcsManagerClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) xfce_mcs_manager_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (XfceMcsManager),
			0 /* n_preallocs */,
			(GInstanceInitFunc) xfce_mcs_manager_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "XfceMcsManager", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((XfceMcsManager *)g_object_new(xfce_mcs_manager_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static XfceMcsManager * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static XfceMcsManager *
GET_NEW_VARG (const char *first, ...)
{
	XfceMcsManager *ret;
	va_list ap;
	va_start (ap, first);
	ret = (XfceMcsManager *)g_object_new_valist (xfce_mcs_manager_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Manager::finalize"
	XfceMcsManager *self  G_GNUC_UNUSED = XFCE_MCS_MANAGER (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#define low (self->low)
#define VAR low
	{
#line 58 "xfce-mcs-manager.gob"
	
			/* hrm..... mcs_manager_destroy (VAR);*/
			VAR = NULL;
		}
#line 176 "xfce-mcs-manager.c"
	memset(&low, 0, sizeof(low));
#undef VAR
#undef low
#define channels (self->channels)
#define VAR channels
	{
#line 64 "xfce-mcs-manager.gob"
	
			g_hash_table_destroy (VAR);
		}
#line 187 "xfce-mcs-manager.c"
	memset(&channels, 0, sizeof(channels));
#undef VAR
#undef channels
#define channels_r (self->channels_r)
#define VAR channels_r
	{
#line 69 "xfce-mcs-manager.gob"
	
			g_hash_table_destroy (VAR);
		}
#line 198 "xfce-mcs-manager.c"
	memset(&channels_r, 0, sizeof(channels_r));
#undef VAR
#undef channels_r
}
#undef __GOB_FUNCTION__

static void 
xfce_mcs_manager_class_init (XfceMcsManagerClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Manager::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	g_object_class->finalize = ___finalize;
}
#undef __GOB_FUNCTION__
#line 92 "xfce-mcs-manager.gob"
static void 
xfce_mcs_manager_init (XfceMcsManager * self G_GNUC_UNUSED)
#line 219 "xfce-mcs-manager.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Manager::init"
#line 50 "xfce-mcs-manager.gob"
	self->low = NULL;
#line 224 "xfce-mcs-manager.c"
 {
#line 93 "xfce-mcs-manager.gob"

		self->channels = g_hash_table_new_full (g_str_hash, my_ascii_strcasecmp,
			g_free, NULL);

		self->channels_r = g_hash_table_new (g_direct_hash, g_direct_equal);
	
#line 233 "xfce-mcs-manager.c"
 }
}
#undef __GOB_FUNCTION__


#line 73 "xfce-mcs-manager.gob"
XfceMcsManager * 
xfce_mcs_manager_new (McsManager * manager)
#line 242 "xfce-mcs-manager.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Manager::new"
{
#line 74 "xfce-mcs-manager.gob"
	
		XfceMcsManager *obj;
		obj = GET_NEW;
		obj->low = manager;
		return obj;
	}}
#line 253 "xfce-mcs-manager.c"
#undef __GOB_FUNCTION__

#line 81 "xfce-mcs-manager.gob"
void 
xfce_mcs_manager_vanish_object (XfceMcsManager * self, GObject * obj)
#line 259 "xfce-mcs-manager.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Manager::vanish_object"
#line 81 "xfce-mcs-manager.gob"
	g_return_if_fail (self != NULL);
#line 81 "xfce-mcs-manager.gob"
	g_return_if_fail (XFCE_IS_MCS_MANAGER (self));
#line 266 "xfce-mcs-manager.c"
{
#line 82 "xfce-mcs-manager.gob"
	
		gchar*	channel_name;
		channel_name = g_hash_table_lookup (self->channels_r, obj);
		g_hash_table_remove (self->channels_r, obj);
		if (channel_name) {
			g_hash_table_remove (self->channels, channel_name);
			/* remove also frees channel_name */
		}
	}}
#line 278 "xfce-mcs-manager.c"
#undef __GOB_FUNCTION__


#line 101 "xfce-mcs-manager.gob"
XfceMcsChannel * 
xfce_mcs_manager_add_channel (XfceMcsManager * self, gchar const * name)
#line 285 "xfce-mcs-manager.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Manager::add_channel"
#line 101 "xfce-mcs-manager.gob"
	g_return_val_if_fail (self != NULL, (XfceMcsChannel * )0);
#line 101 "xfce-mcs-manager.gob"
	g_return_val_if_fail (XFCE_IS_MCS_MANAGER (self), (XfceMcsChannel * )0);
#line 292 "xfce-mcs-manager.c"
{
#line 102 "xfce-mcs-manager.gob"
	
		gpointer	obj;
		gchar*		xname;
		obj = g_hash_table_lookup (self->channels, name);

		if (obj)
			return XFCE_MCS_CHANNEL (obj);

		obj = xfce_mcs_channel_new (self, XFCE_MCS_CHANNEL_SIDE_MANAGER, name);
		g_object_weak_ref ((GObject *)obj, weak_notify_cb, self);
		xname = g_strdup (name);
		g_hash_table_insert (self->channels, xname, obj);
		g_hash_table_insert (self->channels_r, obj, xname);
		return obj;
	}}
#line 310 "xfce-mcs-manager.c"
#undef __GOB_FUNCTION__

#line 118 "xfce-mcs-manager.gob"
void 
xfce_mcs_manager_delete_channel (XfceMcsManager * self, gchar const * name)
#line 316 "xfce-mcs-manager.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Manager::delete_channel"
#line 118 "xfce-mcs-manager.gob"
	g_return_if_fail (self != NULL);
#line 118 "xfce-mcs-manager.gob"
	g_return_if_fail (XFCE_IS_MCS_MANAGER (self));
#line 323 "xfce-mcs-manager.c"
{
#line 119 "xfce-mcs-manager.gob"
	
		if (!self->low) {
			g_warning ("XfceMcsManager: delete_channel: property screen not set.");
			return;
		}
		mcs_manager_delete_channel (self->low, name);
	}}
#line 333 "xfce-mcs-manager.c"
#undef __GOB_FUNCTION__

#line 128 "xfce-mcs-manager.gob"
McsSetting * 
xfce_mcs_manager_get_setting (XfceMcsManager * self, gchar const * channel_name, gchar const * name)
#line 339 "xfce-mcs-manager.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Manager::get_setting"
#line 128 "xfce-mcs-manager.gob"
	g_return_val_if_fail (self != NULL, (McsSetting * )0);
#line 128 "xfce-mcs-manager.gob"
	g_return_val_if_fail (XFCE_IS_MCS_MANAGER (self), (McsSetting * )0);
#line 346 "xfce-mcs-manager.c"
{
#line 129 "xfce-mcs-manager.gob"
	
		McsSetting*	setting;
		setting = mcs_manager_setting_lookup (self->low, name, channel_name);

		return setting;
	}}
#line 355 "xfce-mcs-manager.c"
#undef __GOB_FUNCTION__

#line 136 "xfce-mcs-manager.gob"
void 
xfce_mcs_manager_set_setting (XfceMcsManager * self, McsSetting * setting, gchar const * channel_name)
#line 361 "xfce-mcs-manager.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Manager::set_setting"
#line 136 "xfce-mcs-manager.gob"
	g_return_if_fail (self != NULL);
#line 136 "xfce-mcs-manager.gob"
	g_return_if_fail (XFCE_IS_MCS_MANAGER (self));
#line 368 "xfce-mcs-manager.c"
{
#line 137 "xfce-mcs-manager.gob"
	
		if (mcs_manager_set_setting (self->low, setting, channel_name) != MCS_SUCCESS) {
			g_warning ("XfceMcsManager: set_setting: could not set");
		}
	}}
#line 376 "xfce-mcs-manager.c"
#undef __GOB_FUNCTION__

#line 143 "xfce-mcs-manager.gob"
void 
xfce_mcs_manager_delete_setting (XfceMcsManager * self, gchar const * channel_name, gchar const * name)
#line 382 "xfce-mcs-manager.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Manager::delete_setting"
#line 143 "xfce-mcs-manager.gob"
	g_return_if_fail (self != NULL);
#line 143 "xfce-mcs-manager.gob"
	g_return_if_fail (XFCE_IS_MCS_MANAGER (self));
#line 389 "xfce-mcs-manager.c"
{
#line 144 "xfce-mcs-manager.gob"
	
		if (mcs_manager_delete_setting (self->low, name, channel_name) != MCS_SUCCESS) {
			g_warning ("XfceMcsManager: set_setting: could not delete");
		}
	}}
#line 397 "xfce-mcs-manager.c"
#undef __GOB_FUNCTION__

#line 150 "xfce-mcs-manager.gob"
void 
xfce_mcs_manager_notify (XfceMcsManager * self, gchar const * channel_name)
#line 403 "xfce-mcs-manager.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Manager::notify"
#line 150 "xfce-mcs-manager.gob"
	g_return_if_fail (self != NULL);
#line 150 "xfce-mcs-manager.gob"
	g_return_if_fail (XFCE_IS_MCS_MANAGER (self));
#line 410 "xfce-mcs-manager.c"
{
#line 151 "xfce-mcs-manager.gob"
	
		if (mcs_manager_notify (self->low, channel_name) != MCS_SUCCESS) {
			g_warning ("XfceMcsManager: set_setting: could not notify");
		}
	}}
#line 418 "xfce-mcs-manager.c"
#undef __GOB_FUNCTION__

#line 157 "xfce-mcs-manager.gob"
void 
xfce_mcs_manager_set_setting_string (XfceMcsManager * self, gchar const * channel_name, gchar const * name, gchar const * value)
#line 424 "xfce-mcs-manager.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Manager::set_setting_string"
#line 157 "xfce-mcs-manager.gob"
	g_return_if_fail (self != NULL);
#line 157 "xfce-mcs-manager.gob"
	g_return_if_fail (XFCE_IS_MCS_MANAGER (self));
#line 431 "xfce-mcs-manager.c"
{
#line 158 "xfce-mcs-manager.gob"
	
		if (mcs_manager_set_string (self->low, name, channel_name, value) != MCS_SUCCESS) {
			g_warning ("XfceMcsManager: set_setting: could not set string");
		}
	}}
#line 439 "xfce-mcs-manager.c"
#undef __GOB_FUNCTION__

#line 164 "xfce-mcs-manager.gob"
void 
xfce_mcs_manager_set_setting_int (XfceMcsManager * self, gchar const * channel_name, gchar const * name, gint value)
#line 445 "xfce-mcs-manager.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Manager::set_setting_int"
#line 164 "xfce-mcs-manager.gob"
	g_return_if_fail (self != NULL);
#line 164 "xfce-mcs-manager.gob"
	g_return_if_fail (XFCE_IS_MCS_MANAGER (self));
#line 452 "xfce-mcs-manager.c"
{
#line 165 "xfce-mcs-manager.gob"
	
		if (mcs_manager_set_int (self->low, name, channel_name, value) != MCS_SUCCESS) {
			g_warning ("XfceMcsManager: set_setting: could not set int");
		}
	}}
#line 460 "xfce-mcs-manager.c"
#undef __GOB_FUNCTION__

#line 171 "xfce-mcs-manager.gob"
void 
xfce_mcs_manager_set_setting_color (XfceMcsManager * self, gchar const * channel_name, gchar const * name, McsColor const * value)
#line 466 "xfce-mcs-manager.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Manager::set_setting_color"
#line 171 "xfce-mcs-manager.gob"
	g_return_if_fail (self != NULL);
#line 171 "xfce-mcs-manager.gob"
	g_return_if_fail (XFCE_IS_MCS_MANAGER (self));
#line 473 "xfce-mcs-manager.c"
{
#line 172 "xfce-mcs-manager.gob"
	
		if (mcs_manager_set_color (self->low, name, channel_name, (McsColor *) value) != MCS_SUCCESS) {
			g_warning ("XfceMcsManager: set_setting: could not set color");
		}
	}}
#line 481 "xfce-mcs-manager.c"
#undef __GOB_FUNCTION__
