/* Generated by GOB (v2.0.9)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>
#ifndef __XFCE_MCS_CLIENT_H__
#define __XFCE_MCS_CLIENT_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



#include <gtk/gtk.h>
#include <libxfce4mcs/mcs-client.h>
#include "xfce-mcs-channel.h"


/*
 * Type checking and casting macros
 */
#define XFCE_TYPE_MCS_CLIENT	(xfce_mcs_client_get_type())
#define XFCE_MCS_CLIENT(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), xfce_mcs_client_get_type(), XfceMcsClient)
#define XFCE_MCS_CLIENT_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), xfce_mcs_client_get_type(), XfceMcsClient const)
#define XFCE_MCS_CLIENT_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), xfce_mcs_client_get_type(), XfceMcsClientClass)
#define XFCE_IS_MCS_CLIENT(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), xfce_mcs_client_get_type ())

#define XFCE_MCS_CLIENT_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), xfce_mcs_client_get_type(), XfceMcsClientClass)

/*
 * Main object structure
 */
#ifndef __TYPEDEF_XFCE_MCS_CLIENT__
#define __TYPEDEF_XFCE_MCS_CLIENT__
typedef struct _XfceMcsClient XfceMcsClient;
#endif
struct _XfceMcsClient {
	GObject __parent__;
	/*< private >*/
	McsClient * low; /* protected */
	GHashTable * channels; /* protected */
	GHashTable * channels_r; /* protected */
	GdkScreen * screen; /* protected */
};

/*
 * Class definition
 */
typedef struct _XfceMcsClientClass XfceMcsClientClass;
struct _XfceMcsClientClass {
	GObjectClass __parent__;
	/*signal*/void (* manager_reconnect) (XfceMcsClient * self);
};


/*
 * Public methods
 */
GType	xfce_mcs_client_get_type	(void);
GObject * 	xfce_mcs_client_get_screen	(XfceMcsClient * self);
void 	xfce_mcs_client_set_screen	(XfceMcsClient * self,
					GObject * val);
void 	xfce_mcs_client_manager_reconnect	(XfceMcsClient * self);
XfceMcsClient * 	xfce_mcs_client_new	(void);
void 	xfce_mcs_client_delete_channel	(XfceMcsClient * self,
					gchar const * name);
XfceMcsChannel * 	xfce_mcs_client_add_channel	(XfceMcsClient * self,
					gchar const * name);
gboolean 	xfce_mcs_client_check_manager	(XfceMcsClient * self);
void 	xfce_mcs_client_show_dialog	(XfceMcsClient * self,
					gchar const * message);

/*
 * Signal connection wrapper macros
 */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define xfce_mcs_client_connect__manager_reconnect(object,func,data)	g_signal_connect(XFCE_MCS_CLIENT(__extension__ ({XfceMcsClient *___object = (object); ___object; })),"manager_reconnect",(GCallback) __extension__ ({void (* ___manager_reconnect) (XfceMcsClient * ___fake___self, gpointer ___data ) = (func); ___manager_reconnect; }), (data))
#define xfce_mcs_client_connect_after__manager_reconnect(object,func,data)	g_signal_connect_after(XFCE_MCS_CLIENT(__extension__ ({XfceMcsClient *___object = (object); ___object; })),"manager_reconnect",(GCallback) __extension__ ({void (* ___manager_reconnect) (XfceMcsClient * ___fake___self, gpointer ___data ) = (func); ___manager_reconnect; }), (data))
#define xfce_mcs_client_connect_data__manager_reconnect(object,func,data,destroy_data,flags)	g_signal_connect_data(XFCE_MCS_CLIENT(__extension__ ({XfceMcsClient *___object = (object); ___object; })),"manager_reconnect",(GCallback) __extension__ ({void (* ___manager_reconnect) (XfceMcsClient * ___fake___self, gpointer ___data ) = (func); ___manager_reconnect; }), (data), (destroy_data), (GConnectFlags)(flags))
#else /* __GNUC__ && !__STRICT_ANSI__ */
#define xfce_mcs_client_connect__manager_reconnect(object,func,data)	g_signal_connect(XFCE_MCS_CLIENT(object),"manager_reconnect",(GCallback)(func),(data))
#define xfce_mcs_client_connect_after__manager_reconnect(object,func,data)	g_signal_connect_after(XFCE_MCS_CLIENT(object),"manager_reconnect",(GCallback)(func),(data))
#define xfce_mcs_client_connect_data__manager_reconnect(object,func,data,destroy_data,flags)	g_signal_connect_data(XFCE_MCS_CLIENT(object),"manager_reconnect",(GCallback)(func),(data),(destroy_data),(GConnectFlags)(flags))
#endif /* __GNUC__ && !__STRICT_ANSI__ */


/*
 * Argument wrapping macros
 */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define XFCE_MCS_CLIENT_PROP_SCREEN(arg)    	"screen", __extension__ ({GObject *z = (arg); z;})
#define XFCE_MCS_CLIENT_GET_PROP_SCREEN(arg)	"screen", __extension__ ({GObject **z = (arg); z;})
#else /* __GNUC__ && !__STRICT_ANSI__ */
#define XFCE_MCS_CLIENT_PROP_SCREEN(arg)    	"screen",(GObject *)(arg)
#define XFCE_MCS_CLIENT_GET_PROP_SCREEN(arg)	"screen",(GObject **)(arg)
#endif /* __GNUC__ && !__STRICT_ANSI__ */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
