/* Generated by GOB (v2.0.9) on Thu May 26 23:55:32 2005
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 9

#define selfp (self->_priv)

#include "xfce-mcs-channel.h"

#include "xfce-mcs-channel-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 1 "xfce-mcs-channel.gob"

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif
#ifdef HAVE_STRING_H
#include <string.h>
#endif
#include <stdlib.h>
#include "xfce-mcs-manager-private.h"
#include "xfce-mcs-client-private.h"

#line 40 "xfce-mcs-channel.c"

#line 13 "xfce-mcs-channel.gob"

#include <gtk/gtk.h>
#include <libxfce4mcs/mcs-common.h>
#include <libxfce4mcs/mcs-client.h>

#ifndef __TYPEDEF_XFCE_MCS_CLIENT__
#define __TYPEDEF_XFCE_MCS_CLIENT__
typedef struct _XfceMcsClient XfceMcsClient;
#endif

#ifndef __TYPEDEF_XFCE_MCS_MANAGER__
#define __TYPEDEF_XFCE_MCS_MANAGER__
typedef struct _XfceMcsManager XfceMcsManager;
#endif


#line 59 "xfce-mcs-channel.c"
static const GEnumValue _xfce_mcs_channel_side_values[] = {
	{ XFCE_MCS_CHANNEL_SIDE_CLIENT, (char *)"XFCE_MCS_CHANNEL_SIDE_CLIENT", (char *)"side-client" },
	{ XFCE_MCS_CHANNEL_SIDE_MANAGER, (char *)"XFCE_MCS_CHANNEL_SIDE_MANAGER", (char *)"side-manager" },
	{ 0, NULL, NULL }
};

GType
xfce_mcs_channel_side_get_type (void)
{
	static GType type = 0;
	if ___GOB_UNLIKELY(type == 0)
		type = g_enum_register_static ("XfceMcsChannelSide", _xfce_mcs_channel_side_values);
	return type;
}

/* self casting macros */
#define SELF(x) XFCE_MCS_CHANNEL(x)
#define SELF_CONST(x) XFCE_MCS_CHANNEL_CONST(x)
#define IS_SELF(x) XFCE_IS_MCS_CHANNEL(x)
#define TYPE_SELF XFCE_TYPE_MCS_CHANNEL
#define SELF_CLASS(x) XFCE_MCS_CHANNEL_CLASS(x)

#define SELF_GET_CLASS(x) XFCE_MCS_CHANNEL_GET_CLASS(x)

/* self typedefs */
typedef XfceMcsChannel Self;
typedef XfceMcsChannelClass SelfClass;

/* here are local prototypes */
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
static void xfce_mcs_channel_class_init (XfceMcsChannelClass * c) G_GNUC_UNUSED;
static McsSetting * xfce_mcs_channel_get_setting_low (XfceMcsChannel * self, gchar const * name) G_GNUC_UNUSED;
static void xfce_mcs_channel_init (XfceMcsChannel * self) G_GNUC_UNUSED;

/*
 * Signal connection wrapper macro shortcuts
 */
#define self_connect__setting_changed(object,func,data)	xfce_mcs_channel_connect__setting_changed((object),(func),(data))
#define self_connect_after__setting_changed(object,func,data)	xfce_mcs_channel_connect_after__setting_changed((object),(func),(data))
#define self_connect_data__setting_changed(object,func,data,destroy_data,flags)	xfce_mcs_channel_connect_data__setting_changed((object),(func),(data),(destroy_data),(flags))

typedef void  (*___Sig1) (XfceMcsChannel *, gchar *, gint , gpointer);

static void
___marshal_Sig1 (GClosure *closure,
	GValue *return_value G_GNUC_UNUSED,
	guint n_param_values,
	const GValue *param_values,
	gpointer invocation_hint G_GNUC_UNUSED,
	gpointer marshal_data)
{
	register ___Sig1 callback;
	register GCClosure *cc = (GCClosure*) closure;
	register gpointer data1, data2;

	g_return_if_fail (n_param_values == 3);

	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = g_value_peek_pointer (param_values + 0);
	} else {
		data1 = g_value_peek_pointer (param_values + 0);
		data2 = closure->data;
	}

	callback = (___Sig1) (marshal_data != NULL ? marshal_data : cc->callback);

	callback ((XfceMcsChannel *)data1,
		(gchar *) g_value_get_string (param_values + 1),
		(gint ) g_value_get_enum (param_values + 2),
		data2);
}


enum {
	SETTING_CHANGED_SIGNAL,
	LAST_SIGNAL
};

enum {
	PROP_0,
	PROP_CHANNEL_NAME
};

static guint object_signals[LAST_SIGNAL] = {0};

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_get_channel_name xfce_mcs_channel_get_channel_name
#define self_setting_changed xfce_mcs_channel_setting_changed
#define self_new xfce_mcs_channel_new
#define self_get_setting_low xfce_mcs_channel_get_setting_low
#define self_get_setting xfce_mcs_channel_get_setting
#define self_get_setting_string xfce_mcs_channel_get_setting_string
#define self_get_setting_color xfce_mcs_channel_get_setting_color
#define self_get_setting_int xfce_mcs_channel_get_setting_int
#define self_set_setting xfce_mcs_channel_set_setting
#define self_delay_notify xfce_mcs_channel_delay_notify
#define self_set_setting_string xfce_mcs_channel_set_setting_string
#define self_set_setting_int xfce_mcs_channel_set_setting_int
#define self_set_setting_color xfce_mcs_channel_set_setting_color
#define self_delete_setting xfce_mcs_channel_delete_setting
#define self_add_channel_from_file xfce_mcs_channel_add_channel_from_file
#define self_save_channel_to_file xfce_mcs_channel_save_channel_to_file
GType
xfce_mcs_channel_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (XfceMcsChannelClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) xfce_mcs_channel_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (XfceMcsChannel),
			0 /* n_preallocs */,
			(GInstanceInitFunc) xfce_mcs_channel_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "XfceMcsChannel", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((XfceMcsChannel *)g_object_new(xfce_mcs_channel_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static XfceMcsChannel * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static XfceMcsChannel *
GET_NEW_VARG (const char *first, ...)
{
	XfceMcsChannel *ret;
	va_list ap;
	va_start (ap, first);
	ret = (XfceMcsChannel *)g_object_new_valist (xfce_mcs_channel_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::finalize"
	XfceMcsChannel *self  G_GNUC_UNUSED = XFCE_MCS_CHANNEL (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#define channel_name (self->channel_name)
#define VAR channel_name
	{
#line 38 "xfce-mcs-channel.gob"
	
			g_free (VAR);
			VAR = NULL;
		}
#line 224 "xfce-mcs-channel.c"
	memset(&channel_name, 0, sizeof(channel_name));
#undef VAR
#undef channel_name
#define client (self->client)
#define VAR client
	{
#line 44 "xfce-mcs-channel.gob"
	
			if (VAR) {
				g_object_unref ((GObject *) VAR);
				VAR = NULL;
			}
		}
#line 238 "xfce-mcs-channel.c"
	memset(&client, 0, sizeof(client));
#undef VAR
#undef client
#define manager (self->manager)
#define VAR manager
	{
#line 52 "xfce-mcs-channel.gob"
	
			if (VAR) {
				g_object_unref ((GObject *) VAR);
				VAR = NULL;
			}
		}
#line 252 "xfce-mcs-channel.c"
	memset(&manager, 0, sizeof(manager));
#undef VAR
#undef manager
}
#undef __GOB_FUNCTION__

static void 
xfce_mcs_channel_class_init (XfceMcsChannelClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	object_signals[SETTING_CHANGED_SIGNAL] =
		g_signal_new ("setting_changed",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_FIRST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (XfceMcsChannelClass, setting_changed),
			NULL, NULL,
			___marshal_Sig1,
			G_TYPE_NONE, 2,
			G_TYPE_STRING,
			G_TYPE_ENUM);
	if ___GOB_UNLIKELY(sizeof(gchar const * ) != sizeof(gchar *) || sizeof(McsAction ) != sizeof(gint ) || parent_class == NULL /* avoid warning */) {
		g_error("xfce-mcs-channel.gob line 69: Type mismatch of \"setting_changed\" signal signature");
	}

	c->setting_changed = NULL;
	g_object_class->finalize = ___finalize;
	g_object_class->get_property = ___object_get_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_string
		("channel_name" /* name */,
		 "channel name" /* nick */,
		 "The MCS channel name" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE));
	g_object_class_install_property (g_object_class,
		PROP_CHANNEL_NAME,
		param_spec);
    }
}
#undef __GOB_FUNCTION__
#line 173 "xfce-mcs-channel.gob"
static void 
xfce_mcs_channel_init (XfceMcsChannel * self G_GNUC_UNUSED)
#line 302 "xfce-mcs-channel.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::init"
#line 13 "xfce-mcs-channel.gob"
	self->channel_name = NULL;
#line 307 "xfce-mcs-channel.c"
#line 38 "xfce-mcs-channel.gob"
	self->client = NULL;
#line 310 "xfce-mcs-channel.c"
#line 44 "xfce-mcs-channel.gob"
	self->manager = NULL;
#line 313 "xfce-mcs-channel.c"
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::get_property"
{
	XfceMcsChannel *self G_GNUC_UNUSED;

	self = XFCE_MCS_CHANNEL (object);

	switch (property_id) {
	case PROP_CHANNEL_NAME:
		{
#line 63 "xfce-mcs-channel.gob"

			g_value_set_string (VAL, self->channel_name);
		
#line 335 "xfce-mcs-channel.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__


#line 63 "xfce-mcs-channel.gob"
gchar * 
xfce_mcs_channel_get_channel_name (XfceMcsChannel * self)
#line 354 "xfce-mcs-channel.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::get_channel_name"
{
#line 59 "xfce-mcs-channel.gob"
		gchar* val; g_object_get (G_OBJECT (self), "channel_name", &val, NULL); return val;
}}
#line 361 "xfce-mcs-channel.c"
#undef __GOB_FUNCTION__

#line 69 "xfce-mcs-channel.gob"
void 
xfce_mcs_channel_setting_changed (XfceMcsChannel * self, gchar const * name, McsAction action)
#line 367 "xfce-mcs-channel.c"
{
	GValue ___param_values[3];
	GValue ___return_val;

memset (&___return_val, 0, sizeof (___return_val));
memset (&___param_values, 0, sizeof (___param_values));

#line 69 "xfce-mcs-channel.gob"
	g_return_if_fail (self != NULL);
#line 69 "xfce-mcs-channel.gob"
	g_return_if_fail (XFCE_IS_MCS_CHANNEL (self));
#line 379 "xfce-mcs-channel.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_STRING);
	g_value_set_static_string (&___param_values[1], (gchar *) name);

	___param_values[2].g_type = 0;
	g_value_init (&___param_values[2], G_TYPE_ENUM);
	g_value_set_enum (&___param_values[2], (gint ) action);

	g_signal_emitv (___param_values,
		object_signals[SETTING_CHANGED_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
	g_value_unset (&___param_values[1]);
	g_value_unset (&___param_values[2]);
}

#line 74 "xfce-mcs-channel.gob"
XfceMcsChannel * 
xfce_mcs_channel_new (gpointer actor, XfceMcsChannelSide side, gchar const * name)
#line 406 "xfce-mcs-channel.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::new"
{
#line 75 "xfce-mcs-channel.gob"
	
		XfceMcsChannel* channel;
		channel = GET_NEW;

		channel->channel_name = g_strdup (name);

		if (side == XFCE_MCS_CHANNEL_SIDE_CLIENT)
			channel->client = (XfceMcsClient*)g_object_ref ((GObject *) actor);
		else if (side == XFCE_MCS_CHANNEL_SIDE_MANAGER)
			channel->manager = (XfceMcsManager*)g_object_ref ((GObject *) actor);
			
		return channel;
	}}
#line 424 "xfce-mcs-channel.c"
#undef __GOB_FUNCTION__

#line 89 "xfce-mcs-channel.gob"
static McsSetting * 
xfce_mcs_channel_get_setting_low (XfceMcsChannel * self, gchar const * name)
#line 430 "xfce-mcs-channel.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::get_setting_low"
#line 89 "xfce-mcs-channel.gob"
	g_return_val_if_fail (self != NULL, (McsSetting * )0);
#line 89 "xfce-mcs-channel.gob"
	g_return_val_if_fail (XFCE_IS_MCS_CHANNEL (self), (McsSetting * )0);
#line 437 "xfce-mcs-channel.c"
{
#line 90 "xfce-mcs-channel.gob"
	
		McsSetting*	setting;
		setting = NULL;
		if (self->client) {
			setting = xfce_mcs_client_get_setting (self->client, self->channel_name, name);
		} else if (self->manager) {
			setting = xfce_mcs_manager_get_setting (self->manager, self->channel_name, name);
		}

		return setting;
	}}
#line 451 "xfce-mcs-channel.c"
#undef __GOB_FUNCTION__

#line 102 "xfce-mcs-channel.gob"
gchar * 
xfce_mcs_channel_get_setting (XfceMcsChannel * self, gchar const * name)
#line 457 "xfce-mcs-channel.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::get_setting"
#line 102 "xfce-mcs-channel.gob"
	g_return_val_if_fail (self != NULL, (gchar * )0);
#line 102 "xfce-mcs-channel.gob"
	g_return_val_if_fail (XFCE_IS_MCS_CHANNEL (self), (gchar * )0);
#line 464 "xfce-mcs-channel.c"
{
#line 103 "xfce-mcs-channel.gob"
	
		McsSetting*	setting;
		setting = self_get_setting_low (self, name);
		if (setting) {
			switch (setting->type) {
			case MCS_TYPE_INT:
				return g_strdup_printf ("%d", setting->data.v_int);

			case MCS_TYPE_STRING:
				if (setting->data.v_string)
					return g_strdup (setting->data.v_string);
				break;
			case MCS_TYPE_COLOR:
				return g_strdup_printf ("(%d,%d,%d,%d)", 
					setting->data.v_color.red, 
					setting->data.v_color.green,
					setting->data.v_color.blue,
					setting->data.v_color.alpha
				);
			}
		}

		return NULL;
	}}
#line 491 "xfce-mcs-channel.c"
#undef __GOB_FUNCTION__

#line 128 "xfce-mcs-channel.gob"
gchar * 
xfce_mcs_channel_get_setting_string (XfceMcsChannel * self, gchar const * name)
#line 497 "xfce-mcs-channel.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::get_setting_string"
#line 128 "xfce-mcs-channel.gob"
	g_return_val_if_fail (self != NULL, (gchar * )0);
#line 128 "xfce-mcs-channel.gob"
	g_return_val_if_fail (XFCE_IS_MCS_CHANNEL (self), (gchar * )0);
#line 504 "xfce-mcs-channel.c"
{
#line 129 "xfce-mcs-channel.gob"
	
		McsSetting*	setting;
		setting = self_get_setting_low (self, name);
		if (setting) {
			if (setting->data.v_string)
				return g_strdup (setting->data.v_string);
		}
		return NULL;
	}}
#line 516 "xfce-mcs-channel.c"
#undef __GOB_FUNCTION__

#line 139 "xfce-mcs-channel.gob"
gboolean 
xfce_mcs_channel_get_setting_color (XfceMcsChannel * self, gchar const * name, McsColor * color)
#line 522 "xfce-mcs-channel.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::get_setting_color"
#line 139 "xfce-mcs-channel.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 139 "xfce-mcs-channel.gob"
	g_return_val_if_fail (XFCE_IS_MCS_CHANNEL (self), (gboolean )0);
#line 529 "xfce-mcs-channel.c"
{
#line 140 "xfce-mcs-channel.gob"
	
		McsSetting*	setting;
		
		(*color).red = 0;
		(*color).green = 0;
		(*color).blue = 0;
		(*color).alpha = 0;
		
		
		setting = self_get_setting_low (self, name);
		if (setting) {
			if (setting->type == MCS_TYPE_COLOR) {
				*color = setting->data.v_color;
				return TRUE;
			}
		}
		return FALSE;
	}}
#line 550 "xfce-mcs-channel.c"
#undef __GOB_FUNCTION__

#line 159 "xfce-mcs-channel.gob"
gboolean 
xfce_mcs_channel_get_setting_int (XfceMcsChannel * self, gchar const * name, int * result)
#line 556 "xfce-mcs-channel.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::get_setting_int"
#line 159 "xfce-mcs-channel.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 159 "xfce-mcs-channel.gob"
	g_return_val_if_fail (XFCE_IS_MCS_CHANNEL (self), (gboolean )0);
#line 563 "xfce-mcs-channel.c"
{
#line 160 "xfce-mcs-channel.gob"
	
		McsSetting*	setting;
		setting = self_get_setting_low (self, name);
		if (setting) {
			if (setting->type == MCS_TYPE_INT) {
				*result = setting->data.v_int;
				return TRUE;
			}
		}

		return FALSE;
	}}
#line 578 "xfce-mcs-channel.c"
#undef __GOB_FUNCTION__


#line 177 "xfce-mcs-channel.gob"
void 
xfce_mcs_channel_set_setting (XfceMcsChannel * self, gchar const * name, gchar const * value)
#line 585 "xfce-mcs-channel.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::set_setting"
#line 177 "xfce-mcs-channel.gob"
	g_return_if_fail (self != NULL);
#line 177 "xfce-mcs-channel.gob"
	g_return_if_fail (XFCE_IS_MCS_CHANNEL (self));
#line 592 "xfce-mcs-channel.c"
{
#line 178 "xfce-mcs-channel.gob"
	 /* only mcs manager */
		McsSetting*	setting;
		McsColor	color;
		if (!self->manager) {
			g_warning ("XfceMcsChannel: cannot set setting. I'm not a mcs manager plugin.");
			return;
		}
		setting = xfce_mcs_manager_get_setting (self->manager, self->channel_name, name);
		if (setting) {
			switch (setting->type) {
			case MCS_TYPE_INT:
				xfce_mcs_channel_set_setting_int (self, name, atoi (value));
				break;
			case MCS_TYPE_COLOR:
				if (sscanf (value, "(%hd,%hd,%hd,%hd)", &color.red, &color.green, 
					&color.blue, &color.alpha) != 4) 
				{
					g_warning ("color format was wrong, expected (red,green,blue,alpha)");
					return;
				}
				xfce_mcs_channel_set_setting_color (self, name, &color);
				/* FIXME memory management ? */
				break;
			default: /* case MCS_TYPE_STRING: */
				xfce_mcs_channel_set_setting_string (self, name, value);
				break;
			}
		} else {
			xfce_mcs_channel_set_setting_string (self, name, value);
		}

		self_delay_notify (self);
	}}
#line 628 "xfce-mcs-channel.c"
#undef __GOB_FUNCTION__

#line 212 "xfce-mcs-channel.gob"
void 
xfce_mcs_channel_delay_notify (XfceMcsChannel * self)
#line 634 "xfce-mcs-channel.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::delay_notify"
#line 212 "xfce-mcs-channel.gob"
	g_return_if_fail (self != NULL);
#line 212 "xfce-mcs-channel.gob"
	g_return_if_fail (XFCE_IS_MCS_CHANNEL (self));
#line 641 "xfce-mcs-channel.c"
{
#line 213 "xfce-mcs-channel.gob"
	
		/* todo delay that a bit */
		if (self->manager)
			xfce_mcs_manager_notify (self->manager, self->channel_name);
	}}
#line 649 "xfce-mcs-channel.c"
#undef __GOB_FUNCTION__

#line 219 "xfce-mcs-channel.gob"
void 
xfce_mcs_channel_set_setting_string (XfceMcsChannel * self, gchar const * name, gchar const * value)
#line 655 "xfce-mcs-channel.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::set_setting_string"
#line 219 "xfce-mcs-channel.gob"
	g_return_if_fail (self != NULL);
#line 219 "xfce-mcs-channel.gob"
	g_return_if_fail (XFCE_IS_MCS_CHANNEL (self));
#line 662 "xfce-mcs-channel.c"
{
#line 220 "xfce-mcs-channel.gob"
	 /* only mcs manager */
		if (self->manager)
			xfce_mcs_manager_set_setting_string (self->manager, self->channel_name, name, value);

		self_delay_notify (self);
	}}
#line 671 "xfce-mcs-channel.c"
#undef __GOB_FUNCTION__

#line 227 "xfce-mcs-channel.gob"
void 
xfce_mcs_channel_set_setting_int (XfceMcsChannel * self, gchar const * name, int value)
#line 677 "xfce-mcs-channel.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::set_setting_int"
#line 227 "xfce-mcs-channel.gob"
	g_return_if_fail (self != NULL);
#line 227 "xfce-mcs-channel.gob"
	g_return_if_fail (XFCE_IS_MCS_CHANNEL (self));
#line 684 "xfce-mcs-channel.c"
{
#line 228 "xfce-mcs-channel.gob"
	 /* only mcs manager */
		if (self->manager)
			xfce_mcs_manager_set_setting_int (self->manager, self->channel_name, name, value);
		self_delay_notify (self);
	}}
#line 692 "xfce-mcs-channel.c"
#undef __GOB_FUNCTION__

#line 234 "xfce-mcs-channel.gob"
void 
xfce_mcs_channel_set_setting_color (XfceMcsChannel * self, gchar const * name, McsColor const * value)
#line 698 "xfce-mcs-channel.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::set_setting_color"
#line 234 "xfce-mcs-channel.gob"
	g_return_if_fail (self != NULL);
#line 234 "xfce-mcs-channel.gob"
	g_return_if_fail (XFCE_IS_MCS_CHANNEL (self));
#line 705 "xfce-mcs-channel.c"
{
#line 235 "xfce-mcs-channel.gob"
	 /* only mcs manager */
		if (self->manager)
			xfce_mcs_manager_set_setting_color (self->manager, self->channel_name, name, value);
			
		self_delay_notify (self);
	}}
#line 714 "xfce-mcs-channel.c"
#undef __GOB_FUNCTION__

#line 242 "xfce-mcs-channel.gob"
void 
xfce_mcs_channel_delete_setting (XfceMcsChannel * self, gchar const * name)
#line 720 "xfce-mcs-channel.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::delete_setting"
#line 242 "xfce-mcs-channel.gob"
	g_return_if_fail (self != NULL);
#line 242 "xfce-mcs-channel.gob"
	g_return_if_fail (XFCE_IS_MCS_CHANNEL (self));
#line 727 "xfce-mcs-channel.c"
{
#line 243 "xfce-mcs-channel.gob"
	 /* only mcs manager */
		if (self->manager)
			xfce_mcs_manager_delete_setting (self->manager, self->channel_name, name);
	}}
#line 734 "xfce-mcs-channel.c"
#undef __GOB_FUNCTION__

#line 248 "xfce-mcs-channel.gob"
void 
xfce_mcs_channel_add_channel_from_file (XfceMcsChannel * self, gchar const * filename)
#line 740 "xfce-mcs-channel.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::add_channel_from_file"
#line 248 "xfce-mcs-channel.gob"
	g_return_if_fail (self != NULL);
#line 248 "xfce-mcs-channel.gob"
	g_return_if_fail (XFCE_IS_MCS_CHANNEL (self));
#line 747 "xfce-mcs-channel.c"
{
#line 249 "xfce-mcs-channel.gob"
	 /* only mcs manager */
		if (self->manager)
			xfce_mcs_manager_add_channel_from_file (self->manager, self->channel_name, filename);
	}}
#line 754 "xfce-mcs-channel.c"
#undef __GOB_FUNCTION__

#line 254 "xfce-mcs-channel.gob"
void 
xfce_mcs_channel_save_channel_to_file (XfceMcsChannel * self, gchar const * filename)
#line 760 "xfce-mcs-channel.c"
{
#define __GOB_FUNCTION__ "Xfce:Mcs:Channel::save_channel_to_file"
#line 254 "xfce-mcs-channel.gob"
	g_return_if_fail (self != NULL);
#line 254 "xfce-mcs-channel.gob"
	g_return_if_fail (XFCE_IS_MCS_CHANNEL (self));
#line 767 "xfce-mcs-channel.c"
{
#line 255 "xfce-mcs-channel.gob"
	 /* only mcs manager */
		if (self->manager)
			xfce_mcs_manager_save_channel_to_file (self->manager, self->channel_name, filename);
	}}
#line 774 "xfce-mcs-channel.c"
#undef __GOB_FUNCTION__
