/* Generated by GOB (v2.0.9)   (do not edit directly) */

#ifndef __XFCE_MCS_CLIENT_PRIVATE_H__
#define __XFCE_MCS_CLIENT_PRIVATE_H__

#include "xfce-mcs-client.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



#include <gtk/gtk.h>
#include <libxfce4mcs/mcs-client.h>
#include "xfce-mcs-channel.h"

#line 62 "xfce-mcs-client.gob"
#line 20 "xfce-mcs-client-private.h"
void 	xfce_mcs_client_vanish_object	(XfceMcsClient * self, GObject * obj);
void 	xfce_mcs_client_setting_changed	(XfceMcsClient * self, gchar const * name, gchar const * channel_name, McsAction action, McsSetting * setting);
McsSetting * 	xfce_mcs_client_get_setting	(XfceMcsClient * self, gchar const * channel_name, gchar const * name);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
