/* Generated by GOB (v2.0.9)   (do not edit directly) */

#ifndef __XFCE_MCS_MANAGER_PRIVATE_H__
#define __XFCE_MCS_MANAGER_PRIVATE_H__

#include "xfce-mcs-manager.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



#include <gtk/gtk.h>
#include <libxfce4mcs/mcs-manager.h>
#include "xfce-mcs-channel.h"

#line 51 "xfce-mcs-manager.gob"
#line 20 "xfce-mcs-manager-private.h"
void 	xfce_mcs_manager_vanish_object	(XfceMcsManager * self, GObject * obj);
McsSetting * 	xfce_mcs_manager_get_setting	(XfceMcsManager * self, gchar const * channel_name, gchar const * name);
void 	xfce_mcs_manager_set_setting	(XfceMcsManager * self, McsSetting * setting, gchar const * channel_name);
void 	xfce_mcs_manager_delete_setting	(XfceMcsManager * self, gchar const * channel_name, gchar const * name);
void 	xfce_mcs_manager_notify	(XfceMcsManager * self, gchar const * channel_name);
void 	xfce_mcs_manager_set_setting_string	(XfceMcsManager * self, gchar const * channel_name, gchar const * name, gchar const * value);
void 	xfce_mcs_manager_set_setting_int	(XfceMcsManager * self, gchar const * channel_name, gchar const * name, gint value);
void 	xfce_mcs_manager_set_setting_color	(XfceMcsManager * self, gchar const * channel_name, gchar const * name, McsColor const * value);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
