/* Generated by GOB (v2.0.9)   (do not edit directly) */

#ifndef __XFCE_MCS_CHANNEL_PRIVATE_H__
#define __XFCE_MCS_CHANNEL_PRIVATE_H__

#include "xfce-mcs-channel.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



#include <gtk/gtk.h>
#include <libxfce4mcs/mcs-common.h>
#include <libxfce4mcs/mcs-client.h>

#ifndef __TYPEDEF_XFCE_MCS_CLIENT__
#define __TYPEDEF_XFCE_MCS_CLIENT__
typedef struct _XfceMcsClient XfceMcsClient;
#endif

#ifndef __TYPEDEF_XFCE_MCS_MANAGER__
#define __TYPEDEF_XFCE_MCS_MANAGER__
typedef struct _XfceMcsManager XfceMcsManager;
#endif


#line 13 "xfce-mcs-channel.gob"
#line 31 "xfce-mcs-channel-private.h"
void 	xfce_mcs_channel_delay_notify	(XfceMcsChannel * self);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
